---
# Local CNS host - this machine
all:
  children:
    cns:
      hosts:
        localhost:
          ansible_connection: local
          ansible_python_interpreter: /usr/bin/python3

      vars:
        cns_k8s_type: kubeadm
        ngc_api_key: "{{ lookup('env', 'NGC_API_KEY') }}"
        renny_replicas: 2
        renny_namespace: uneeq
        gpu_timeslice_replicas: 4
        phoenix_enabled: true
        prometheus_enabled: true
        nim_operator_enabled: true
