{{- if or .Values.secrets.httpServiceApiKey .Values.secrets.deepgramApiKey }}
apiVersion: v1
kind: Secret
metadata:
  name: digitalhuman-websocket-api
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  {{- if .Values.secrets.httpServiceApiKey }}
  HTTP_SERVICE_API_KEY: {{ .Values.secrets.httpServiceApiKey | quote }}
  {{- end }}
  {{- if .Values.secrets.deepgramApiKey }}
  DEEPGRAM_API_KEY: {{ .Values.secrets.deepgramApiKey | quote }}
  {{- end }}
{{- end }}
