apiVersion: v1
kind: Service
metadata:
  name: digitalhuman-websocket-api
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: digitalhuman-websocket-api
  ports:
  - port: {{ .Values.service.httpPort }}
    targetPort: {{ .Values.service.httpPort }}
    protocol: TCP
    name: http
  - port: {{ .Values.service.wsPort }}
    targetPort: {{ .Values.service.wsPort }}
    protocol: TCP
    name: ws
