################################################################################
# Copyright (c) 2022, NVIDIA CORPORATION.  All rights reserved.
# NVIDIA Corporation and its licensors retain all intellectual property
# and proprietary rights in and to this software, related documentation
# and any modifications thereto.  Any use, reproduction, disclosure or
# distribution of this software and related documentation without an express
# license agreement from NVIDIA Corporation is strictly prohibited.
################################################################################

common:
  # How often should FPS logs be printed per stream
  fps_logging_interval_second: 1
  garbage_collector:
    # enable or disable the garbage collector
    enabled: true
    # how often the garbage collector should run
    interval_run_second: 5
    # If when the garbage collector runs, some streams contain
    # more than N second of data then, the data is removed
    # until the storage goes below that number
    # client is supposed to read everything and not make this
    # service hold the data for too long
    # 60 seconds means ~80mb of ram
    max_size_stored_data_second: 30
  stream_number: 2
  add-silence-padding-after-audio: true
  export-params-to-animdata: false
  queue-size-after-streammux: 1
  queue-size-after-a2f: 15
  queue-size-after-a2e: 1500

audio2x:
  # where audio2X is located
  send-audio:
    ip: audio2face_with_emotion
    port: 50000
  # which port to open to receive animation data
  receive-anim-data:
    port: 52100

animgraph:
  # true is animgraph is enabled, false otherwise
  enabled: false
  # where to connect to animgraph
  send-http:
    ip: 0.0.0.0
    port: 8020

public-interface:
  # port exposed publicly to the outside of the cluster
  # The provided python app connects to it
  port: 52000

grpc_input:
  port: 50000

grpc_output:
  ip: audio2face_controller
  port: 52100

A2E:
  enabled: false
  inference-interval: 16

A2F:
  model_path: "/opt/nvidia/a2x_pipeline/a2f_data/data/networks/claire_v1.3"
  enabled: true
  max_30_fps: true
  emotions:
    a2e-multiplier: 0.5
    external-multiplier: 0.5
    max-update-step: 0.08
