apiVersion: v1
kind: Service
metadata:
  name: digitalhuman-asr
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: digitalhuman-asr
  ports:
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.proxy.port }}
    protocol: TCP
    name: ws
