apiVersion: v1
kind: Secret
metadata:
  namespace: {{ .Release.Namespace }}
  name: renderer
data:
  # These are optional and can potentially be removed? @mohsen
  cp-flowise-api-key: {{ .Values.renderer.cp.flowiseApiKey | default ""  }}
  tts-veritone-api-key: {{ .Values.renderer.tts.veritoneApiKey | default ""  }}
  launch-darkly-key: {{ .Values.renderer.launchDarkly.key | default ""  }}

  # These are required
  dhop-api-key: {{ .Values.renderer.dhop.apiKey }}
  tts-azure-speech-key: {{ .Values.renderer.tts.azureSpeechKey }}
  tts-elevenlabs-api-key: {{ .Values.renderer.tts.elevenlabsApiKey }}
  tts-gcp-creds: {{ .Values.renderer.tts.gcpCredentials | default ""  }}
