apiVersion: v1
kind: ConfigMap
metadata:
  name: renny-telemetry
  namespace: {{ .Release.Namespace }}
  labels:
    app: renderer
data:
  telemetry-client.sh: |
{{ .Files.Get "scripts/renny-telemetry-client.sh" | indent 4 }}
